/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAiRouteImport } from './routes/api.ai'
import { Route as AppTranslatorRouteImport } from './routes/_app.translator'
import { Route as AppStaysRouteImport } from './routes/_app.stays'
import { Route as AppShieldRouteImport } from './routes/_app.shield'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppFlightsRouteImport } from './routes/_app.flights'
import { Route as AppDealsRouteImport } from './routes/_app.deals'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTranslatorRoute = AppTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => AppRoute,
} as any)
const AppStaysRoute = AppStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => AppRoute,
} as any)
const AppShieldRoute = AppShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppFlightsRoute = AppFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRoute
  '/flights': typeof AppFlightsRoute
  '/planner': typeof AppPlannerRoute
  '/shield': typeof AppShieldRoute
  '/stays': typeof AppStaysRoute
  '/translator': typeof AppTranslatorRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRoute
  '/flights': typeof AppFlightsRoute
  '/planner': typeof AppPlannerRoute
  '/shield': typeof AppShieldRoute
  '/stays': typeof AppStaysRoute
  '/translator': typeof AppTranslatorRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deals': typeof AppDealsRoute
  '/_app/flights': typeof AppFlightsRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/shield': typeof AppShieldRoute
  '/_app/stays': typeof AppStaysRoute
  '/_app/translator': typeof AppTranslatorRoute
  '/api/ai': typeof ApiAiRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/deals'
    | '/flights'
    | '/planner'
    | '/shield'
    | '/stays'
    | '/translator'
    | '/api/ai'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/deals'
    | '/flights'
    | '/planner'
    | '/shield'
    | '/stays'
    | '/translator'
    | '/api/ai'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/deals'
    | '/_app/flights'
    | '/_app/planner'
    | '/_app/shield'
    | '/_app/stays'
    | '/_app/translator'
    | '/api/ai'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/translator': {
      id: '/_app/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AppTranslatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stays': {
      id: '/_app/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof AppStaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shield': {
      id: '/_app/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof AppShieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flights': {
      id: '/_app/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AppFlightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealsRoute: typeof AppDealsRoute
  AppFlightsRoute: typeof AppFlightsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppShieldRoute: typeof AppShieldRoute
  AppStaysRoute: typeof AppStaysRoute
  AppTranslatorRoute: typeof AppTranslatorRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDealsRoute: AppDealsRoute,
  AppFlightsRoute: AppFlightsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppShieldRoute: AppShieldRoute,
  AppStaysRoute: AppStaysRoute,
  AppTranslatorRoute: AppTranslatorRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAiRoute: ApiAiRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
